quarkus:
  http:
    port: 8080
    cors: true

jambit:
  message: "Hello Universe"

at:
  java:
    name: "Peter"
    email: "Peter@office.de"
    address: "Germany"

"%profile-A":
  jambit:
    message: "Hello Profile A"

"%profile-B":
  jambit:
    message: "Hello Profile B"