### public
GET http://localhost:8080/api/secured/public

### authenticated (unortherized)
GET http://localhost:8080/api/secured/authenticated

### authenticated (autherized) - use CreateJwt test for token
GET http://localhost:8080/api/secured/authenticated
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2V4YW1wbGUuY29tL2lzc3VlciIsInVwbiI6IlVzZXJQcmluY2lwbGVOYW1lIiwiZ3JvdXBzIjpbIlVzZXIiLCJBZG1pbiJdLCJiaXJ0aGRhdGUiOiIxOTk4LTExLTAyIiwiaWF0IjoxNjUzMDQ2OTc2LCJleHAiOjE2NTMxMzMzNzYsImp0aSI6ImI0ZTJlMjI4LTMxOTEtNGYxMS04ZjRjLTI1YjQ5NzkxMThjNCJ9.mtUh6P5Y_PLfItrxZSiGvoK7s3SUR8cOMgVb_zF6JnxwDS41hiORLZmEU9tnx0l_E4PlNafHWWjgb4VvdaV1tFJXqSSMkDKeI_4LvVrbrpnqS5os1_63gDu3cG-7IMVurdnSBe6gVxJ9D3b1G-_FAIe-2Z999YYFxzzKlex5PAj9zgvhpipXVd4T3TOMAiwg9Sr1efHHm0EKcKWgz77BZtgirSwtuwFcYF1lPpiqh9BFb-D-c382gwhon0ePG5bFMKZkk2Ip9w3ymL3JyE2EHK2g4gWpDjUCmVyAHUrBAXSWGonFRqfT-3MJneWiws7KjC8lYgE91szIWv0zXGqSEw

### role admin (autherized) - use CreateJwt test for token
GET http://localhost:8080/api/secured/admin
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2V4YW1wbGUuY29tL2lzc3VlciIsInVwbiI6IlVzZXJQcmluY2lwbGVOYW1lIiwiZ3JvdXBzIjpbIlVzZXIiLCJBZG1pbiJdLCJiaXJ0aGRhdGUiOiIxOTk4LTExLTAyIiwiaWF0IjoxNjUzMDQ2OTc2LCJleHAiOjE2NTMxMzMzNzYsImp0aSI6ImI0ZTJlMjI4LTMxOTEtNGYxMS04ZjRjLTI1YjQ5NzkxMThjNCJ9.mtUh6P5Y_PLfItrxZSiGvoK7s3SUR8cOMgVb_zF6JnxwDS41hiORLZmEU9tnx0l_E4PlNafHWWjgb4VvdaV1tFJXqSSMkDKeI_4LvVrbrpnqS5os1_63gDu3cG-7IMVurdnSBe6gVxJ9D3b1G-_FAIe-2Z999YYFxzzKlex5PAj9zgvhpipXVd4T3TOMAiwg9Sr1efHHm0EKcKWgz77BZtgirSwtuwFcYF1lPpiqh9BFb-D-c382gwhon0ePG5bFMKZkk2Ip9w3ymL3JyE2EHK2g4gWpDjUCmVyAHUrBAXSWGonFRqfT-3MJneWiws7KjC8lYgE91szIWv0zXGqSEw

### role admin (autherized) - use CreateJwt test for token
GET http://localhost:8080/api/secured/other
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2V4YW1wbGUuY29tL2lzc3VlciIsInVwbiI6IlVzZXJQcmluY2lwbGVOYW1lIiwiZ3JvdXBzIjpbIlVzZXIiLCJBZG1pbiJdLCJiaXJ0aGRhdGUiOiIxOTk4LTExLTAyIiwiaWF0IjoxNjUzMDQ2OTc2LCJleHAiOjE2NTMxMzMzNzYsImp0aSI6ImI0ZTJlMjI4LTMxOTEtNGYxMS04ZjRjLTI1YjQ5NzkxMThjNCJ9.mtUh6P5Y_PLfItrxZSiGvoK7s3SUR8cOMgVb_zF6JnxwDS41hiORLZmEU9tnx0l_E4PlNafHWWjgb4VvdaV1tFJXqSSMkDKeI_4LvVrbrpnqS5os1_63gDu3cG-7IMVurdnSBe6gVxJ9D3b1G-_FAIe-2Z999YYFxzzKlex5PAj9zgvhpipXVd4T3TOMAiwg9Sr1efHHm0EKcKWgz77BZtgirSwtuwFcYF1lPpiqh9BFb-D-c382gwhon0ePG5bFMKZkk2Ip9w3ymL3JyE2EHK2g4gWpDjUCmVyAHUrBAXSWGonFRqfT-3MJneWiws7KjC8lYgE91szIWv0zXGqSEw

